const ActionTypes = {
  AUTH_USER: 'AUTH_USER',
  DEAUTH_USER: 'DEAUTH_USER',
  SEARCH: 'SEARCH',

  FETCH_RESOURCE: 'FETCH_RESOURCE',
  FETCH_RESOURCES: 'FETCH_RESOURCES',
  // DELETE_RESOURCES: 'DELETE_RESOURCES',

  FETCH_USER: 'FETCH_USER',
  FETCH_USERS: 'FETCH_USERS',

};

export default ActionTypes;
